# FortiGate performance metrics

[[inputs.snmp]]
  agents = [""]
  version = 2
  community = "${FORTIGATE_SNMP_COMMUNITY}"
  timeout = "5s"
  retries = 2
  interval = "30s"
  name = "fortigate_performance"

  [inputs.snmp.tags]
    customer = "st-brigids"
    site = "st-brigids"
    vendor = "fortinet"
    platform = "fortigate"
    device_role = "firewall"
    device_ip = ""

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "1.3.6.1.2.1.1.5.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "firmware"
    oid = "1.3.6.1.4.1.12356.101.4.1.1.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "cpu_percent"
    oid = "1.3.6.1.4.1.12356.101.4.1.3.0"

  [[inputs.snmp.field]]
    name = "memory_percent"
    oid = "1.3.6.1.4.1.12356.101.4.1.4.0"

  [[inputs.snmp.field]]
    name = "memory_capacity_kb"
    oid = "1.3.6.1.4.1.12356.101.4.1.5.0"

  [[inputs.snmp.field]]
    name = "disk_used_mb"
    oid = "1.3.6.1.4.1.12356.101.4.1.6.0"

  [[inputs.snmp.field]]
    name = "disk_capacity_mb"
    oid = "1.3.6.1.4.1.12356.101.4.1.7.0"

  [[inputs.snmp.field]]
    name = "active_sessions"
    oid = "1.3.6.1.4.1.12356.101.4.1.8.0"

  [[inputs.snmp.field]]
    name = "session_setup_rate"
    oid = "1.3.6.1.4.1.12356.101.4.1.11.0"
