apiVersion: 1

datasources:
  - name: ITP Runtime Values
    uid: itp-runtime-values
    type: grafana-testdata-datasource
    access: proxy
    editable: false

  - name: influxdb
    uid: ffsu5ap2kr5dse
    type: influxdb
    access: proxy
    url: http://influxdb3-core:8181
    isDefault: true
    editable: false
    jsonData:
      version: SQL
      dbName: ${INFLUXDB_BUCKET}
      httpMode: POST
      insecureGrpc: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
