sites:
  - id: st-brigids-lesmurdie
    display_name: "St Brigid's College, Lesmurdie"
    aliases:
      - SBC
      - st-brigids
      - "St Brigid's College"
      - "St Brigid's College, Lesmurdie P2P"

  - id: MLC
    display_name: "Methodist Ladies College"
    aliases:
      - MLC
      - Methodist Ladies College
      - any-name-returned-by-snmp
