sites:
  - id: st-brigids-lesmurdie
    display_name: "Northwind College"
    aliases:
      - SBC
      - st-brigids
      - "Northwind College"
      - "Northwind College P2P"

  - id: MLC
    display_name: "Greenwood College"
    aliases:
      - MLC
      - Methodist Ladies' College
