# Copyright 2025 InfluxData

[global_tags]
  deployment_id = "${ITP_DEPLOYMENT_ID}"

[agent]
  interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  flush_interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  hostname = "${HOSTNAME}"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = true

[[inputs.mem]]

[[inputs.disk]]
  mount_points = ["/"]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.diskio]]
  devices = ["sda", "sdb", "nvme0n1"]
  skip_serial_number = true

[[inputs.net]]
  interfaces = ["eth*", "en*"]
  ignore_protocol_stats = false

[[inputs.system]]

[[outputs.influxdb_v2]]
  urls = ["http://${INFLUXDB_HOST}:8181"]
  token = "${INFLUXDB_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"
